# Generated by Django 4.2a1 on 2023-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ServiceUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("is_bot", models.BooleanField()),
                ("username", models.CharField(max_length=32, null=True)),
                ("first_name", models.CharField(max_length=64, null=True)),
                ("last_name", models.CharField(max_length=64, null=True)),
                ("language_code", models.CharField(max_length=3, null=True)),
                ("phone_number", models.CharField(max_length=15, null=True)),
            ],
        )
    ]
