# Generated by Django 4.2a1 on 2023-02-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0002_serviceuser")]

    operations = [
        migrations.AddField(model_name="serviceuser", name="is_premium", field=models.BooleanField(null=True))
    ]
