# Generated by Django 4.2a1 on 2023-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0003_serviceuser_is_premium")]

    operations = [
        migrations.AlterField(
            model_name="serviceuser", name="is_premium", field=models.BooleanField(default=False, null=True)
        )
    ]
