# Generated by Django 4.2a1 on 2023-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0005_bankaccount_card")]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name="card", name="balance", field=models.DecimalField(decimal_places=2, default=0, max_digits=32)
        ),
    ]
