# Generated by Django 4.2b1 on 2023-03-10 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_bankaccount_balance_card_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="corr_account",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="inn",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="kpp",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="rcbic",
        ),
        migrations.RemoveField(
            model_name="card",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="card",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="serviceuser",
            name="is_bot",
        ),
        migrations.RemoveField(
            model_name="serviceuser",
            name="is_premium",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="user",
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to="app.serviceuser"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="account",
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to="app.bankaccount"),
            preserve_default=False,
        ),
    ]
