image: docker/compose:debian-1.29.2

stages:
  - build
  - lint
  - deploy

before_script:
  - apt-get update
  - apt-get install -y make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cp $DOT_ENV $(pwd)/.env

build:
  stage: build
  script:
    - make build push
  tags:
    - job:build
  only:
    - master
  environment:
    name: prod

lint:
  stage: lint
  script:
    - apt-get update
    - apt-get install -y isort
    - apt-get install -y flake8
    - make check_lint
  tags:
    - job:lint
  only:
    - master
  environment:
    name: prod

deploy:
  stage: deploy
  script:
    - make pull down migrate up
  tags:
    - job:deploy.prod/1
  only:
    - master
  environment:
    name: prod
  when: manual