version: "3.8"
services:
  postgres:
    image: "postgres:12.14-alpine"
    hostname: "${POSTGRES_HOST}"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"
    env_file: 
      - "./.env"

  app-server:
    image: "${CI_REGISTRY}/ilya.grubenuk/ci-cd/ci-cd:${CI_ENVIRONMENT_SLUG}-${CI_COMMIT_SHA}"
    depends_on:
      - "postgres"
    command: -c "/wait && make"
    environment:
      WAIT_HOSTS: "${POSTGRES_HOST}:5432"
    env_file:
      - "./.env"
    ports:
      - "${SERVER_PORT}:8000"

  app-bot:
    image: "${CI_REGISTRY}/ilya.grubenuk/ci-cd/ci-cd:${CI_ENVIRONMENT_SLUG}-${CI_COMMIT_SHA}"
    depends_on:
      - "app-server"
    command: -c "make runbot"
    env_file:
      - "./.env"

volumes:
  postgres_volume:
