version: "3.8"
services:
  app:
    build: ./src
    command: python manage.py runall 0.0.0.0:8000 
    volumes:
      - ./src:/home/appuser/
    ports:
      - 8000:8000
    env_file:
      - ./.env.compose
  db:
    image: postgres:12.14-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file: 
      - ./.env.psql

volumes:
  postgres_volume:
